# Generated by Django 5.1.4 on 2024-12-25 20:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-sold_at']},
        ),
        migrations.AlterModelOptions(
            name='salesperson',
            options={'ordering': ['user__first_name']},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='created_at',
            new_name='added_at',
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'shop')},
        ),
        migrations.RemoveField(
            model_name='sale',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='sold_by',
        ),
        migrations.RemoveField(
            model_name='salesperson',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='salesperson',
            name='role',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='location',
        ),
        migrations.AddField(
            model_name='product',
            name='inventory',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='+', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='salesperson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='shop.salesperson'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesperson',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='salesperson',
            name='hire_date',
            field=models.DateField(default='2024-10-10'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer_name',
            field=models.CharField(default='+', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='shop.product'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='quantity',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salespersons', to='shop.shop'),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shop',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_shops', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='shop.shop')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'shop')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.productcategory'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
