# Generated by Django 5.1.4 on 2024-12-25 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_sale_options_rename_sold_at_sale_sale_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.productcategory'),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='hire_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
