# Generated by Django 5.1.4 on 2024-12-25 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_category_alter_salesperson_hire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
