# Generated by Django 5.1.4 on 2024-12-25 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_saleitem_unit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='total_price',
        ),
    ]
