# Generated by Django 5.1.4 on 2025-01-19 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_sale_shop_alter_sale_salesperson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='salesperson',
        ),
        migrations.DeleteModel(
            name='SalesPerson',
        ),
    ]
