# Generated by Django 5.1.4 on 2025-01-20 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_remove_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='address',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
